// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbiiEIdr0VD8ad06I9FOt2EipmtQMVVsQ',
    appId: '1:202538657778:web:bd1924341196c134c5ed6b',
    messagingSenderId: '202538657778',
    projectId: 'prueb-7393f',
    authDomain: 'prueb-7393f.firebaseapp.com',
    storageBucket: 'prueb-7393f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6uiRueegRn-HqQPJDL3FA9w2tHSMPJUg',
    appId: '1:202538657778:android:13a7b3bef27557ddc5ed6b',
    messagingSenderId: '202538657778',
    projectId: 'prueb-7393f',
    storageBucket: 'prueb-7393f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJ_uquUQ9meNjffRcGo0Dh5c-IkV-HE0',
    appId: '1:202538657778:ios:200b4305c3e36092c5ed6b',
    messagingSenderId: '202538657778',
    projectId: 'prueb-7393f',
    storageBucket: 'prueb-7393f.appspot.com',
    iosClientId: '202538657778-httkl76gb4ip94fh8e94sm190lus79c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJ_uquUQ9meNjffRcGo0Dh5c-IkV-HE0',
    appId: '1:202538657778:ios:200b4305c3e36092c5ed6b',
    messagingSenderId: '202538657778',
    projectId: 'prueb-7393f',
    storageBucket: 'prueb-7393f.appspot.com',
    iosClientId: '202538657778-httkl76gb4ip94fh8e94sm190lus79c5.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );
}
